<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>ToyoStageService</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseVSHostingProcess>false</UseVSHostingProcess>
    <AssemblyTitle>StageServerConfig</AssemblyTitle>
    <Product>StageServerConfig</Product>
    <Copyright>Copyright ©  2019</Copyright>
    <InformationalVersion>StageServerConfig 1.22.08.xx [.NET Framework 4.8]</InformationalVersion>
    <PlatformTarget>x64</PlatformTarget>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StageServerConfig\FieldInfoControl.cs" Link="FieldInfoControl.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StageServerConfig\GetSubHostServerMode.cs" Link="GetSubHostServerMode.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StageServerConfig\MemoryMappedFileControl.cs" Link="MemoryMappedFileControl.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StageServerConfig\RemoteServerCommand_GetSetValue.cs" Link="RemoteServerCommand_GetSetValue.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StageServerConfig\SharedConfigValue.cs" Link="SharedConfigValue.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StageServerConfig\StageServerConfig.cs" Link="StageServerConfig.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StageServerConfig\StageServerConfigInfo.cs" Link="StageServerConfigInfo.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StageServerConfig\StageServerConfigWork.cs" Link="StageServerConfigWork.cs" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="ProgramData（サーバー側設定ファイル）\TOYOCOMMON\StageServerConfig.XML" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\SasaLibDNet8\SasaLibDNet8\SasaLibDNet8.csproj" />
    <ProjectReference Include="..\..\..\SasaLibTestFrame\SasaLib.DelegateWriteLine\SasaLib.DelegateWriteLine.csproj" />
    <ProjectReference Include="..\DefineCOMDS\DefineCOMDS.DNet8.csproj" />
    <ProjectReference Include="..\SharedClassLibrary\SharedClassLibraryDNet8.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
</Project>