<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD_ApprovalRecepitonState_Client.cs" Link="CMD_ApprovalRecepitonState_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD_CommitRecepitonState_Client.cs" Link="CMD_CommitRecepitonState_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD_ConnectTest_Client.cs" Link="CMD_ConnectTest_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD_DataBaseSearch3_Client.cs" Link="CMD_DataBaseSearch3_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD_DataBaseSearch4a_Client.cs" Link="CMD_DataBaseSearch4a_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD_GetArcSuiteAtrtribute1_Client.cs" Link="CMD_GetArcSuiteAtrtribute1_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD_GetArcSuiteAtrtribute2_Client.cs" Link="CMD_GetArcSuiteAtrtribute2_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD_GetArcSuiteAtrtribute3_Client.cs" Link="CMD_GetArcSuiteAtrtribute3_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD_GetArcSuiteAtrtribute_Client .cs" Link="CMD_GetArcSuiteAtrtribute_Client .cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD_GetArcSuiteLatestDrawingFile_Client.cs" Link="CMD_GetArcSuiteLatestDrawingFile_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD_GetArcSuiteLatestDrawing_Client.cs" Link="CMD_GetArcSuiteLatestDrawing_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD_GetCommitPrinterIsFailStatus_Client.cs" Link="CMD_GetCommitPrinterIsFailStatus_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD_GetCommitPrinterNameAndAlias_Client.cs" Link="CMD_GetCommitPrinterNameAndAlias_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD_GetCommitPrinterSettingFromPaperSize_Client.cs" Link="CMD_GetCommitPrinterSettingFromPaperSize_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD_GetCommitPrinterShortCutNameAndDescription_Client.cs" Link="CMD_GetCommitPrinterShortCutNameAndDescription_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD_GetCommitPrinterShortCutName_Client.cs" Link="CMD_GetCommitPrinterShortCutName_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD_GetVersion_Client.cs" Link="CMD_GetVersion_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD_LoadImage2_Client.cs" Link="CMD_LoadImage2_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD_LoadImage_Client.cs" Link="CMD_LoadImage_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD_ServerControl_FileRecv_Client.cs" Link="CMD_ServerControl_FileRecv_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD_ServerControl_FileSend_Client.cs" Link="CMD_ServerControl_FileSend_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD_ServerControl_GetFileList_Client.cs" Link="CMD_ServerControl_GetFileList_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD_Status_SERVER_ALIVE_Client.cs" Link="CMD_Status_SERVER_ALIVE_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\DummyParam.cs" Link="DummyParam.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\ServerInfo.cs" Link="ServerInfo.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD_CommandSample_Client.cs" Link="CMD_CommandSample_Client.cs" />
	    </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="8.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\SasaLibDNet8\SasaLibDNet8\SasaLibDNet8.csproj" />
    <ProjectReference Include="..\DefineCOMDS\DefineCOMDS.DNet8.csproj" />
    <ProjectReference Include="..\RemoteObjects\RemoteObjectsDNet8.csproj" />
    <ProjectReference Include="..\StreamCommandBridge\StreamCommandBridgeDNet8.csproj" />
  </ItemGroup>

</Project>
