<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net8.0-windows</TargetFramework>
	  <OutputType>Library</OutputType>
	  <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandBridge\CommandContextExtensions.cs" Link="CommandContextExtensions.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandBridge\CommandLoggingExtensions.cs" Link="CommandLoggingExtensions.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandBridge\CommandTimingExtensions.cs" Link="CommandTimingExtensions.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandBridge\ConnectionType.cs" Link="ConnectionType.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandBridge\ICommandContext.cs" Link="ICommandContext.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandBridge\SequenceNumberProvider.cs" Link="SequenceNumberProvider.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandBridge\ServerAssignmentRequestDto.cs" Link="ServerAssignmentRequestDto.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandBridge\StreamBasedClient\CommandStreamContext.cs" Link="StreamBasedClient\CommandStreamContext.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandBridge\StreamBasedClient\IStreamProvider.cs" Link="StreamBasedClient\IStreamProvider.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandBridge\StreamBasedClient\StreamBasedClient.cs" Link="StreamBasedClient\StreamBasedClient.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandBridge\StreamBasedClient\StreamProvider_Pipe.cs" Link="StreamBasedClient\StreamProvider_Pipe.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandBridge\StreamBasedClient\StreamProvider_Tcp.cs" Link="StreamBasedClient\StreamProvider_Tcp.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandBridge\StreamBasedServer\CommandContext_Pipe.cs" Link="StreamBasedServer\CommandContext_Pipe.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandBridge\StreamBasedServer\CommandContext_Tcp.cs" Link="StreamBasedServer\CommandContext_Tcp.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandBridge\StreamBasedServer\StreamBasedServer.cs" Link="StreamBasedServer\StreamBasedServer.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandBridge\StreamBasedServer\StreamBasedServerLauncher.cs" Link="StreamBasedServer\StreamBasedServerLauncher.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandBridge\StreamBasedServer\StreamBasedTestValue.cs" Link="StreamBasedServer\StreamBasedTestValue.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandBridge\StreamStringSequencedExtensions.cs" Link="StreamStringSequencedExtensions.cs" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="StreamBasedServer\" />
    <Folder Include="StreamBasedClient\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\SasaLibDNet8\SasaLibDNet8\SasaLibDNet8.csproj" />
    <ProjectReference Include="..\DefineCOMDS\DefineCOMDS.DNet8.csproj" />
    <ProjectReference Include="..\SharedClassLibrary\SharedClassLibraryDNet8.csproj" />
    <ProjectReference Include="..\StageServerCommon\StageServerCommonDNet8.csproj" />
    <ProjectReference Include="..\StageServerConfig\StageServerConfigDNet8.csproj" />
  </ItemGroup>

</Project>
