<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>SasaImagePrinter</AssemblyName>
    <RootNamespace>SasaImagePrinter</RootNamespace>
    <Configurations>Debug;Release;Debug-2027;Release-2027</Configurations>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Install.ps1" />
    <None Remove="README.md" />
    <None Remove="Uninstall.ps1" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Install.ps1">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="README.md">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Uninstall.ps1">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
