<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
	  <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	  <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD01_ApprovalRecepitonState_Client.cs" Link="CMD01_ApprovalRecepitonState_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD02_ClientPreInputTicketCodeAdd_Client.cs" Link="CMD02_ClientPreInputTicketCodeAdd_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD03_ClientPreInputTicketCodeRemove_Client.cs" Link="CMD03_ClientPreInputTicketCodeRemove_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD04_CommandSample_Client.cs" Link="CMD04_CommandSample_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD05a_CommitRecepitonState_Client.cs" Link="CMD05a_CommitRecepitonState_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD05_CommitRecepitonState_Client.cs" Link="CMD05_CommitRecepitonState_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD06_ConnectTest_Client.cs" Link="CMD06_ConnectTest_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD07a_DataBaseSearch2_Client.cs" Link="CMD07a_DataBaseSearch2_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD07b_DataBaseSearch3_Client.cs" Link="CMD07b_DataBaseSearch3_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD08_DataBaseSearch4a_Client.cs" Link="CMD08_DataBaseSearch4a_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD09_DR_GetAuthorizedUser_Client.cs" Link="CMD09_DR_GetAuthorizedUser_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD10_GetArcSuiteAtrtribute_Client .cs" Link="CMD10_GetArcSuiteAtrtribute_Client .cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD11_GetArcSuiteAtrtribute1_Client.cs" Link="CMD11_GetArcSuiteAtrtribute1_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD12_GetArcSuiteAtrtribute2_Client.cs" Link="CMD12_GetArcSuiteAtrtribute2_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD13_GetArcSuiteAtrtribute3_Client.cs" Link="CMD13_GetArcSuiteAtrtribute3_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD14_GetArcSuiteLatestDrawing_Client.cs" Link="CMD14_GetArcSuiteLatestDrawing_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD15_GetArcSuiteLatestDrawingFile_Client.cs" Link="CMD15_GetArcSuiteLatestDrawingFile_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD16_GetCommitPrinterIsFailStatus_Client.cs" Link="CMD16_GetCommitPrinterIsFailStatus_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD17_GetCommitPrinterNameAndAlias_Client.cs" Link="CMD17_GetCommitPrinterNameAndAlias_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD18_GetCommitPrinterSettingFromPaperSizes_Client.cs" Link="CMD18_GetCommitPrinterSettingFromPaperSizes_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD19_GetCommitPrinterShortCutName_Client.cs" Link="CMD19_GetCommitPrinterShortCutName_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD20_GetCommitPrinterShortCutNameAndDescription_Client.cs" Link="CMD20_GetCommitPrinterShortCutNameAndDescription_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD21_GetVersion_Client.cs" Link="CMD21_GetVersion_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD22_LoadImage_Client.cs" Link="CMD22_LoadImage_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD23_LoadImage2_Client.cs" Link="CMD23_LoadImage2_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD24_ServerControl_FileRecv_Client.cs" Link="CMD24_ServerControl_FileRecv_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD25_ServerControl_FileSend_Client.cs" Link="CMD25_ServerControl_FileSend_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD26_ServerControl_GetFileList_Client.cs" Link="CMD26_ServerControl_GetFileList_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD27_Status_ARCSUITE_SERVERHOST_Client.cs" Link="CMD27_Status_ARCSUITE_SERVERHOST_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD28_Status_SERVER_ALIVE_Client.cs" Link="CMD28_Status_SERVER_ALIVE_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD29_Status_SERVER_CURRENT_MODE_Client.cs" Link="CMD29_Status_SERVER_CURRENT_MODE_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD30_Status_SERVER_MODE_MasterOrSlave_Client.cs" Link="CMD30_Status_SERVER_MODE_MasterOrSlave_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD31_GetArcSuiteAwaitingRegist_Client.cs" Link="CMD31_GetArcSuiteAwaitingRegist_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD33_GetCommonApprovalWaitingTicketList_Client.cs" Link="CMD33_GetCommonApprovalWaitingTicketList_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD34_Approved2c_Client.cs" Link="CMD34_Approved2c_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD35_DataBaseUpdate_Client.cs" Link="CMD35_DataBaseUpdate_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD36_ApprovedCancels3_Client.cs" Link="CMD36_ApprovedCancels3_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD37_GetPipeCommandLog_Client.cs" Link="CMD37_GetPipeCommandLog_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD38_ConsoleLogLevelGet_Client.cs" Link="CMD38_ConsoleLogLevelGet_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD39_ConsoleLogLevelSet_Client.cs" Link="CMD39_ConsoleLogLevelSet_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD40_ReloadStageServerConfig_Client.cs" Link="CMD40_ReloadStageServerConfig_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD41_SaveStageServerConfig_Client.cs" Link="CMD41_SaveStageServerConfig_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD42_SaveStageServerDatabaseConfig_Client.cs" Link="CMD42_SaveStageServerDatabaseConfig_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD43_ReloadStampConf_Client.cs" Link="CMD43_ReloadStampConf_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD44_ReloadBarcodeConf_Client.cs" Link="CMD44_ReloadBarcodeConf_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD45_SetCommitAcceptFalseMsg_Client.cs" Link="CMD45_SetCommitAcceptFalseMsg_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD46_GetCommitAcceptFalseMsg_Client.cs" Link="CMD46_GetCommitAcceptFalseMsg_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD47_SetApprovingAcceptFalseMsg_Client.cs" Link="CMD47_SetApprovingAcceptFalseMsg_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD48_GetApprovingAcceptFalseMsg_Client.cs" Link="CMD48_GetApprovingAcceptFalseMsg_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD49_GetBackupStatus_Client.cs" Link="CMD49_GetBackupStatus_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD50_GetRestoreStatus_Client.cs" Link="CMD50_GetRestoreStatus_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD51_DatabaseBackup_Client.cs" Link="CMD51_DatabaseBackup_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD52_DatabaseRestore_Client.cs" Link="CMD52_DatabaseRestore_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD53_ServiceStop_Client.cs" Link="CMD53_ServiceStop_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD54_GetActiveSessionCommandList_Client.cs" Link="CMD54_GetActiveSessionCommandList_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD55_StressTest_Client.cs" Link="CMD55_StressTest_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD56_GetServerVersion_Client.cs" Link="CMD56_GetServerVersion_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD57_ReloadStageServerDatabaseConfig_Client.cs" Link="CMD57_ReloadStageServerDatabaseConfig_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD58_GetValue_Client.cs" Link="CMD58_GetValue_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD59_SetValue_Client.cs" Link="CMD59_SetValue_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD60_GetVauleList_Client.cs" Link="CMD60_GetVauleList_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD61_CreateTicketCode_Client.cs" Link="CMD61_CreateTicketCode_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD62_GetCommitPrinterInfo_Client.cs" Link="CMD62_GetCommitPrinterInfo_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD63_LoadTextFile_Client.cs" Link="CMD63_LoadTextFile_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD64_CheckDrawingType_Client.cs" Link="CMD64_CheckDrawingType_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD65_GetCommitFolder_Client.cs" Link="CMD65_GetCommitFolder_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD66_MailSendLogLevelSet_Client.cs" Link="CMD66_MailSendLogLevelSet_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD67_GetArcSuiteAtrtributeFromObjectID_Client.cs" Link="CMD67_GetArcSuiteAtrtributeFromObjectID_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD68_RecordAndEntityfileDelete_Client.cs" Link="CMD68_RecordAndEntityfileDelete_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD69_GetArcSuiteContents_Client.cs" Link="CMD69_GetArcSuiteContents_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD70_SetRegistWaitingFlag2_Client.cs" Link="CMD70_SetRegistWaitingFlag2_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD71_ShowPrinterQueue_Client.cs" Link="CMD71_ShowPrinterQueue_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD72_TitleFieldTest_Client.cs" Link="CMD72_TitleFieldTest_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD73_DC_TEST1_Client.cs" Link="CMD73_DC_TEST1_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD74_GetAvailableMemory_Client.cs" Link="CMD74_GetAvailableMemory_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD75_GetMemoryUsageWorkingSetSize_Client.cs" Link="CMD75_GetMemoryUsageWorkingSetSize_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD76_GetArcSuiteAttributeFromOBJECTIDList_Client.cs" Link="CMD76_GetArcSuiteAttributeFromOBJECTIDList_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD77_MergeArcSuiteAtrtribute_Client.cs" Link="CMD77_MergeArcSuiteAtrtribute_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD78_GetArcSuiteLatestDrawingFiles_Client.cs" Link="CMD78_GetArcSuiteLatestDrawingFiles_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD79_SaveArcSuiteTicketConfig_Client.cs" Link="CMD79_SaveArcSuiteTicketConfig_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD80_BulkRecordAndEntityfileDeleteByDate_Client.cs" Link="CMD80_BulkRecordAndEntityfileDeleteByDate_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD81_FileStoreCheck_Client.cs" Link="CMD81_FileStoreCheck_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD82_FileStoreRepare_Client.cs" Link="CMD82_FileStoreRepare_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD83_TicketFileExistCheck_Client.cs" Link="CMD83_TicketFileExistCheck_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD84_GetMmapValue_Client.cs" Link="CMD84_GetMmapValue_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD85_SetMmapValue_Client.cs" Link="CMD85_SetMmapValue_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD86_SendTestMail_Client.cs" Link="CMD86_SendTestMail_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD87_PrintStart_Client.cs" Link="CMD87_PrintStart_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\DummyParam.cs" Link="DummyParam.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\ServerInfo.cs" Link="ServerInfo.cs" />
	    </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="8.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\SasaLibDNet8\SasaLibDNet8\SasaLibDNet8.csproj" />
    <ProjectReference Include="..\DefineCOMDS\DefineCOMDS.DNet8.csproj" />
    <ProjectReference Include="..\RemoteObjects\RemoteObjectsDNet8.csproj" />
    <ProjectReference Include="..\StageServerConfig\StageServerConfigDNet8.csproj" />  
	<ProjectReference Include="..\StreamCommandBridge\StreamCommandBridgeDNet8.csproj" />
  </ItemGroup>

  <Import Project="..\..\STAGINGSYSTEM_ShareDNet8.AssemblyInfo\STAGINGSYSTEMDNet8.AssemblyInfo.projitems" Label="Shared" />

</Project>
