<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD01_ApprovalRecepitonState_Client.cs" Link="CMD01_ApprovalRecepitonState_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD02_ClientPreInputTicketCodeAdd_Client.cs" Link="CMD02_ClientPreInputTicketCodeAdd_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD03_ClientPreInputTicketCodeRemove_Client.cs" Link="CMD03_ClientPreInputTicketCodeRemove_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD04_CommandSample_Client.cs" Link="CMD04_CommandSample_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD05_CommitRecepitonState_Client.cs" Link="CMD05_CommitRecepitonState_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD06_ConnectTest_Client.cs" Link="CMD06_ConnectTest_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD07a_DataBaseSearch2_Client.cs" Link="CMD07a_DataBaseSearch2_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD07b_DataBaseSearch3_Client.cs" Link="CMD07b_DataBaseSearch3_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD08_DataBaseSearch4a_Client.cs" Link="CMD08_DataBaseSearch4a_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD09_DR_GetAuthorizedUser_Client.cs" Link="CMD09_DR_GetAuthorizedUser_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD10_GetArcSuiteAtrtribute_Client .cs" Link="CMD10_GetArcSuiteAtrtribute_Client .cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD11_GetArcSuiteAtrtribute1_Client.cs" Link="CMD11_GetArcSuiteAtrtribute1_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD12_GetArcSuiteAtrtribute2_Client.cs" Link="CMD12_GetArcSuiteAtrtribute2_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD13_GetArcSuiteAtrtribute3_Client.cs" Link="CMD13_GetArcSuiteAtrtribute3_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD14_GetArcSuiteLatestDrawing_Client.cs" Link="CMD14_GetArcSuiteLatestDrawing_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD15_GetArcSuiteLatestDrawingFile_Client.cs" Link="CMD15_GetArcSuiteLatestDrawingFile_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD16_GetCommitPrinterIsFailStatus_Client.cs" Link="CMD16_GetCommitPrinterIsFailStatus_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD17_GetCommitPrinterNameAndAlias_Client.cs" Link="CMD17_GetCommitPrinterNameAndAlias_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD18_GetCommitPrinterSettingFromPaperSizes_Client.cs" Link="CMD18_GetCommitPrinterSettingFromPaperSizes_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD19_GetCommitPrinterShortCutName_Client.cs" Link="CMD19_GetCommitPrinterShortCutName_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD20_GetCommitPrinterShortCutNameAndDescription_Client.cs" Link="CMD20_GetCommitPrinterShortCutNameAndDescription_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD21_GetVersion_Client.cs" Link="CMD21_GetVersion_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD22_LoadImage_Server_Client.cs" Link="CMD22_LoadImage_Server_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD23_LoadImage2_Client.cs" Link="CMD23_LoadImage2_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD24_ServerControl_FileRecv_Client.cs" Link="CMD24_ServerControl_FileRecv_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD25_ServerControl_FileSend_Client.cs" Link="CMD25_ServerControl_FileSend_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD26_ServerControl_GetFileList_Client.cs" Link="CMD26_ServerControl_GetFileList_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD27_Status_ARCSUITE_SERVERHOST_Client.cs" Link="CMD27_Status_ARCSUITE_SERVERHOST_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD28_Status_SERVER_ALIVE_Client.cs" Link="CMD28_Status_SERVER_ALIVE_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD29_Status_SERVER_CURRENT_MODE_Client.cs" Link="CMD29_Status_SERVER_CURRENT_MODE_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD30_Status_SERVER_MODE_MasterOrSlave_Client.cs" Link="CMD30_Status_SERVER_MODE_MasterOrSlave_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD31_GetArcSuiteAwaitingRegist_Client.cs" Link="CMD31_GetArcSuiteAwaitingRegist_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD33_GetCommonApprovalWaitingTicketList_Client.cs" Link="CMD33_GetCommonApprovalWaitingTicketList_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\DummyParam.cs" Link="DummyParam.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\ServerInfo.cs" Link="ServerInfo.cs" />
	    </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="8.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\SasaLibDNet8\SasaLibDNet8\SasaLibDNet8.csproj" />
    <ProjectReference Include="..\DefineCOMDS\DefineCOMDS.DNet8.csproj" />
    <ProjectReference Include="..\RemoteObjects\RemoteObjectsDNet8.csproj" />  
	<ProjectReference Include="..\StageServerConfig\StageServerConfigDNet8.csproj" />  
	<ProjectReference Include="..\StreamCommandBridge\StreamCommandBridgeDNet8.csproj" />
  </ItemGroup>

</Project>
