<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<Deterministic>false</Deterministic>
	  <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	  <Deterministic>false</Deterministic>
	  <UseWPF>true</UseWPF>
	  <UseWindowsForms>true</UseWindowsForms>
	  <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <UseVSHostingProcess>false</UseVSHostingProcess>
    <AssemblyTitle>RemoteClient</AssemblyTitle>
    <InformationalVersion>RemoteClient 1.22.08.xx [.NET Framework 4.8]</InformationalVersion>
    <PlatformTarget>x64</PlatformTarget>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD_CommitRecepitonState_Client.cs" Link="CMD_CommitRecepitonState_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD_GetArcSuiteAtrtribute1_Client.cs" Link="CMD_GetArcSuiteAtrtribute1_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD_GetArcSuiteAtrtribute2_Client.cs" Link="CMD_GetArcSuiteAtrtribute2_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD_GetArcSuiteAtrtribute3_Client.cs" Link="CMD_GetArcSuiteAtrtribute3_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD_GetArcSuiteAtrtribute_Client .cs" Link="CMD_GetArcSuiteAtrtribute_Client .cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD_GetArcSuiteLatestDrawingFile_Client.cs" Link="CMD_GetArcSuiteLatestDrawingFile_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD_GetArcSuiteLatestDrawing_Client.cs" Link="CMD_GetArcSuiteLatestDrawing_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD_GetCommitPrinterSettingFromPaperSize_Client.cs" Link="CMD_GetCommitPrinterSettingFromPaperSize_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD_GetVersion_Client.cs" Link="CMD_GetVersion_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD_LoadImage2_Client.cs" Link="CMD_LoadImage2_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD_LoadImage_Client.cs" Link="CMD_LoadImage_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD_ServerControl_FileRecv_Client.cs" Link="CMD_ServerControl_FileRecv_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD_ServerControl_FileSend_Client.cs" Link="CMD_ServerControl_FileSend_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\CMD_ServerControl_GetFileList_Client.cs" Link="CMD_ServerControl_GetFileList_Client.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\DummyParam.cs" Link="DummyParam.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorClient\ServerInfo.cs" Link="ServerInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\SasaLibDNet8\SasaLibDNet8\SasaLibDNet8.csproj" />
    <ProjectReference Include="..\DefineCOMDS\DefineCOMDS.DNet8.csproj" />
    <ProjectReference Include="..\FieldValueSet\FieldValueSetDNet8.csproj" />
    <ProjectReference Include="..\RemoteObjects\RemoteObjectsDNet8.csproj" />
    <ProjectReference Include="..\SharedClassLibrary\SharedClassLibraryDNet8.csproj" />
    <ProjectReference Include="..\StreamCommandBridge\StreamCommandBridgeDNet8.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Buffers" Version="4.6.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
    <PackageReference Include="System.IO.Packaging" Version="9.0.0" />
    <PackageReference Include="System.Management" Version="9.0.0" />
    <PackageReference Include="System.Memory" Version="4.6.0" />
  </ItemGroup>
  <Import Project="..\..\STAGINGSYSTEM.AssemblyVersion\SasaLibDNet8.AssemblyVersion.projitems" Label="Shared" />
</Project>