<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net8.0-windows</TargetFramework>
	  <OutputType>Library</OutputType>
	  <ImplicitUsings>enable</ImplicitUsings>
	  <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD01_ApprovalRecepitonState_Server.cs" Link="CMD01_ApprovalRecepitonState_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD02_ClientPreInputTicketCodeAdd_Server.cs" Link="CMD02_ClientPreInputTicketCodeAdd_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD03_ClientPreInputTicketCodeRemove_Server.cs" Link="CMD03_ClientPreInputTicketCodeRemove_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD04_CommandSample_Server.cs" Link="CMD04_CommandSample_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD05_CommitRecepitonState2_Server.cs" Link="CMD05_CommitRecepitonState2_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD05_CommitRecepitonState_Server.cs" Link="CMD05_CommitRecepitonState_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD06_ConnectTest_Server.cs" Link="CMD06_ConnectTest_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD07a_DataBaseSearch2_Server.cs" Link="CMD07a_DataBaseSearch2_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD07_DataBaseSearch3_Server.cs" Link="CMD07_DataBaseSearch3_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD08_DataBaseSearch4a_Server.cs" Link="CMD08_DataBaseSearch4a_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD09_DR_GetAuthorizedUser_Server.cs" Link="CMD09_DR_GetAuthorizedUser_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD10_GetArcSuiteAtrtribute_Server.cs" Link="CMD10_GetArcSuiteAtrtribute_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD11_GetArcSuiteAtrtribute1_Server.cs" Link="CMD11_GetArcSuiteAtrtribute1_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD12_GetArcSuiteAtrtribute2_Server.cs" Link="CMD12_GetArcSuiteAtrtribute2_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD13_GetArcSuiteAtrtribute3_Server.cs" Link="CMD13_GetArcSuiteAtrtribute3_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD14_GetArcSuiteLatestDrawing_Server.cs" Link="CMD14_GetArcSuiteLatestDrawing_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD15_GetArcSuiteLatestDrawingFile_Server.cs" Link="CMD15_GetArcSuiteLatestDrawingFile_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD16_GetCommitPrinterIsFailStatus_Server.cs" Link="CMD16_GetCommitPrinterIsFailStatus_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD17_GetCommitPrinterNameAndAlias_Server.cs" Link="CMD17_GetCommitPrinterNameAndAlias_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD18_GetCommitPrinterSettingFromPaperSizes_Server.cs" Link="CMD18_GetCommitPrinterSettingFromPaperSizes_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD19_GetCommitPrinterShortCutName_Server.cs" Link="CMD19_GetCommitPrinterShortCutName_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD20_GetCommitPrinterShortCutNameAndDescription_Server.cs" Link="CMD20_GetCommitPrinterShortCutNameAndDescription_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD21_GetVersion_Server.cs" Link="CMD21_GetVersion_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD22_LoadImage_Server.cs" Link="CMD22_LoadImage_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD23_LoadImage2_Server.cs" Link="CMD23_LoadImage2_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD24_ServerControl_FileRecv_Server.cs" Link="CMD24_ServerControl_FileRecv_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD25_ServerControl_FileSend_Server.cs" Link="CMD25_ServerControl_FileSend_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD26_ServerControl_GetFileList_Server.cs" Link="CMD26_ServerControl_GetFileList_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD27_Status_ARCSUITE_SERVERHOST_Server.cs" Link="CMD27_Status_ARCSUITE_SERVERHOST_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD28_Status_SERVER_ALIVE_Server.cs" Link="CMD28_Status_SERVER_ALIVE_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD29_Status_SERVER_CURRENT_MODE_Server.cs" Link="CMD29_Status_SERVER_CURRENT_MODE_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD30_Status_SERVER_MODE_MasterOrSlave_Server.cs" Link="CMD30_Status_SERVER_MODE_MasterOrSlave_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD31_GetArcSuiteAwaitingRegist_Server.cs" Link="CMD31_GetArcSuiteAwaitingRegist_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD33_GetCommonApprovalWaitingTicketList_Server.cs" Link="CMD33_GetCommonApprovalWaitingTicketList_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD34_Approved2c_Server.cs" Link="CMD34_Approved2c_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD35_DataBaseUpdate_Server.cs" Link="CMD35_DataBaseUpdate_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD36_ApprovedCancels3_Server.cs" Link="CMD36_ApprovedCancels3_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD37_GetPipeCommandLog_Server.cs" Link="CMD37_GetPipeCommandLog_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD38_ConsoleLogLevelGet_Server.cs" Link="CMD38_ConsoleLogLevelGet_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD39_ConsoleLogLevelSet_Server.cs" Link="CMD39_ConsoleLogLevelSet_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD40_ReloadStageServerConfig_Server.cs" Link="CMD40_ReloadStageServerConfig_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD41_SaveStageServerConfig_Server.cs" Link="CMD41_SaveStageServerConfig_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD42_SaveStageServerDatabaseConfig_Server.cs" Link="CMD42_SaveStageServerDatabaseConfig_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD43_ReloadStampConf_Server.cs" Link="CMD43_ReloadStampConf_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD44_ReloadBarcodeConf_Server.cs" Link="CMD44_ReloadBarcodeConf_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD45_SetCommitAcceptFalseMsg_Server.cs" Link="CMD45_SetCommitAcceptFalseMsg_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD46_GetCommitAcceptFalseMsg_Server.cs" Link="CMD46_GetCommitAcceptFalseMsg_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD47_SetApprovingAcceptFalseMsg_Server.cs" Link="CMD47_SetApprovingAcceptFalseMsg_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD48_GetApprovingAcceptFalseMsg_Server.cs" Link="CMD48_GetApprovingAcceptFalseMsg_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD49_GetBackupStatus_Server.cs" Link="CMD49_GetBackupStatus_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD50_GetRestoreStatus_Server.cs" Link="CMD50_GetRestoreStatus_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD51_DatabaseBackup_Server.cs" Link="CMD51_DatabaseBackup_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD52_DatabaseRestore_Server.cs" Link="CMD52_DatabaseRestore_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD53_ServiceStop_Server.cs" Link="CMD53_ServiceStop_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD54_GetActiveSessionCommandList_Server.cs" Link="CMD54_GetActiveSessionCommandList_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD55_StressTest_Server.cs" Link="CMD55_StressTest_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD56_GetServerVersion_Server.cs" Link="CMD56_GetServerVersion_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD57_ReloadStageServerDatabaseConfig_Server.cs" Link="CMD57_ReloadStageServerDatabaseConfig_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD58_GetValue_Server.cs" Link="CMD58_GetValue_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD59_SetValue_Server.cs" Link="CMD59_SetValue_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD60_GetVauleList_Server.cs" Link="CMD60_GetVauleList_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD61_CreateTicketCode_Server.cs" Link="CMD61_CreateTicketCode_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD62_GetCommitPrinterInfo_Server.cs" Link="CMD62_GetCommitPrinterInfo_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD63_LoadTextFile_Server.cs" Link="CMD63_LoadTextFile_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD64_CheckDrawingType_Server.cs" Link="CMD64_CheckDrawingType_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD65_GetCommitFolder_Server.cs" Link="CMD65_GetCommitFolder_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD66_MailSendLogLevelSet_Server.cs" Link="CMD66_MailSendLogLevelSet_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD67_GetArcSuiteAtrtributeFromObjectID_Server.cs" Link="CMD67_GetArcSuiteAtrtributeFromObjectID_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD68_RecordAndEntityfileDelete_Server.cs" Link="CMD68_RecordAndEntityfileDelete_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD69_GetArcSuiteContents_Server.cs" Link="CMD69_GetArcSuiteContents_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD70_SetRegistWaitingFlag2_Server.cs" Link="CMD70_SetRegistWaitingFlag2_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD71_ShowPrinterQueue_Server.cs" Link="CMD71_ShowPrinterQueue_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD72_TitleFieldTest_Server.cs" Link="CMD72_TitleFieldTest_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD73_DC_TEST1_Server.cs" Link="CMD73_DC_TEST1_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD74_GetAvailableMemory_Server.cs" Link="CMD74_GetAvailableMemory_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD75_GetMemoryUsageWorkingSetSize_Server.cs" Link="CMD75_GetMemoryUsageWorkingSetSize_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD76_GetArcSuiteAttributeFromOBJECTIDList_Server.cs" Link="CMD76_GetArcSuiteAttributeFromOBJECTIDList_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD77_MergeArcSuiteAtrtribute_Server.cs" Link="CMD77_MergeArcSuiteAtrtribute_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD78_GetArcSuiteLatestDrawingFiles_Server.cs" Link="CMD78_GetArcSuiteLatestDrawingFiles_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD79_SaveArcSuiteTicketConfig_Server.cs" Link="CMD79_SaveArcSuiteTicketConfig_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD80_BulkRecordAndEntityfileDeleteByDate_Server.cs" Link="CMD80_BulkRecordAndEntityfileDeleteByDate_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD81_FileStoreCheck_Server.cs" Link="CMD81_FileStoreCheck_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD82_FileStoreRepare_Server.cs" Link="CMD82_FileStoreRepare_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD83_TicketFileExistCheck_Server.cs" Link="CMD83_TicketFileExistCheck_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD84_GetMmapValue_Server.cs" Link="CMD84_GetMmapValue_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD85_SetMmapValue_Server.cs" Link="CMD85_SetMmapValue_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD86_SendTestMail_Server.cs" Link="CMD86_SendTestMail_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CMD87_PrintStart_Server.cs" Link="CMD87_PrintStart_Server.cs" />
    <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\StreamCommandExecutorServer\CommandExecutor.cs" Link="CommandExecutor.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\SasaLibDNet8\SasaLibDNet8\SasaLibDNet8.csproj" />
    <ProjectReference Include="..\..\..\SasaLibTestFrame\Barcode_src_1.0.0.21\BarcodeLib\BarcodeLib.csproj" />
    <ProjectReference Include="..\ApprovedSystemDNet8\ApprovedSystemDNet8.csproj" />
    <ProjectReference Include="..\ArcSuiteSdkDnet8\ArcSuiteSdkDNet8.csproj" />
    <ProjectReference Include="..\DefineCOMDS\DefineCOMDS.DNet8.csproj" />
    <ProjectReference Include="..\SharedClassLibrary\SharedClassLibraryDNet8.csproj" />
    <ProjectReference Include="..\StageServerCommon\StageServerCommonDNet8.csproj" />
    <ProjectReference Include="..\StageServerConfig\StageServerConfigDNet8.csproj" />
    <ProjectReference Include="..\StageServerPrinterService\StageServerPrinterServiceDNet8.csproj" />
    <ProjectReference Include="..\StreamCommandBridge\StreamCommandBridgeDNet8.csproj" />
  </ItemGroup>

</Project>
