<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<OutputType>Library</OutputType>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<Deterministic>false</Deterministic>
		<UseVSHostingProcess>false</UseVSHostingProcess>
		<AssemblyTitle>SharedClassLibrary</AssemblyTitle>
		<Nullable>disable</Nullable>
		<PlatformTarget>x64</PlatformTarget>
		<AssemblyName>SharedClassLibrary</AssemblyName>
		<RootNamespace>ToyoStageService</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
	  <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\SharedClassLibrary\AcceptPipeCommand.cs" Link="AcceptPipeCommand.cs" />
	  <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\SharedClassLibrary\ClientPreInputTICKET.cs" Link="ClientPreInputTICKET.cs" />
	  <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\SharedClassLibrary\CommonSqlSyntax.cs" Link="CommonSqlSyntax.cs" />
	  <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\SharedClassLibrary\ConsoleOption.cs" Link="ConsoleOption.cs" />
	  <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\SharedClassLibrary\DebugClass.cs" Link="DebugClass.cs" />
	  <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\SharedClassLibrary\GlovalValues.cs" Link="GlovalValues.cs" />
	  <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\SharedClassLibrary\PresentTicketCode.cs" Link="PresentTicketCode.cs" />
	  <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\SharedClassLibrary\PrinterInfo.cs" Link="PrinterInfo.cs" />
	  <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\SharedClassLibrary\PrinterStatus.cs" Link="PrinterStatus.cs" />
	  <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\SharedClassLibrary\ServerLog.cs" Link="ServerLog.cs" />
	  <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\SharedClassLibrary\SharedClassLibraryInfo.cs" Link="SharedClassLibraryInfo.cs" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\..\SasaLibDNet8\SasaLibDNet8\SasaLibDNet8.csproj" />
		<ProjectReference Include="..\..\..\SasaLibTestFrame\SasaLib.DelegateWriteLine\SasaLib.DelegateWriteLine.csproj" />
		<ProjectReference Include="..\FieldValueSet\FieldValueSetDNet8.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
		<PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
	</ItemGroup>
	<ItemGroup>
		<Folder Include="Properties\" />
	</ItemGroup>
	<Import Project="..\..\..\AutocadTOYOaddinCommitDNet8\AssemblyInfo\AssemblyInfo.projitems" Label="Shared" />
</Project>