<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<OutputType>Library</OutputType>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
		<AssemblyTitle>CommonCommitDialog</AssemblyTitle>
		<Copyright></Copyright>
		<PlatformTarget>x64</PlatformTarget>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<Deterministic>false</Deterministic>
		<Nullable>disable</Nullable>
		<RootNamespace>CommonCommitLogic</RootNamespace>
	</PropertyGroup>
	<ItemGroup>
	  <None Remove="TESTFILE\XX-12345-701~720.dwg" />
	  <None Remove="TESTFILE\XX-12345-993.dwg" />
	  <None Remove="TESTFILE\XX-12345-998RL.dwg" />
	</ItemGroup>
	<ItemGroup>
	  <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\CommonCommitLogic\ArcSuiteSearchResult.cs" Link="ArcSuiteSearchResult.cs" />
	  <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\CommonCommitLogic\CadDrawingFIle.cs" Link="CadDrawingFIle.cs" />
	  <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\CommonCommitLogic\Commit.cs" Link="Commit.cs" />
	  <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\CommonCommitLogic\CommitCommonSettings.cs" Link="CommitCommonSettings.cs" />
	  <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\CommonCommitLogic\CommitHelper.cs" Link="CommitHelper.cs" />
	  <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\CommonCommitLogic\CommitHelperArcSuite.cs" Link="CommitHelperArcSuite.cs" />
	  <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\CommonCommitLogic\CommitHelperCadDrawingFile.cs" Link="CommitHelperCadDrawingFile.cs" />
	  <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\CommonCommitLogic\CommitHelperNumbering.cs" Link="CommitHelperNumbering.cs" />
	  <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\CommonCommitLogic\CommitHelperNumbering_Partial.cs" Link="CommitHelperNumbering_Partial.cs" />
	  <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\CommonCommitLogic\ReserveNumber.cs" Link="ReserveNumber.cs" />
	  <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\CommonCommitLogic\TestForm1.cs" Link="TestForm1.cs" />
	  <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\CommonCommitLogic\TestForm1.Designer.cs" Link="TestForm1.Designer.cs" />
	  <Compile Include="..\..\..\TOYOSTAGINGSYSTEM\STAGINGSYSTEM_Share\CommonCommitLogic\TypeNumber.cs" Link="TypeNumber.cs" />
	</ItemGroup>
	<ItemGroup>
	  <Content Include="TESTFILE\XX-12345-701~720.dwg" />
	  <Content Include="TESTFILE\XX-12345-993.dwg" />
	  <Content Include="TESTFILE\XX-12345-998RL.dwg" />
	</ItemGroup>
	<ItemGroup>
		<Compile Update="CommitPreviewImage.cs">
			<SubType>UserControl</SubType>
		</Compile>
		<Compile Update="Properties\Settings.Designer.cs">
		  <DesignTimeSharedInput>True</DesignTimeSharedInput>
		  <AutoGen>True</AutoGen>
		  <DependentUpon>Settings.settings</DependentUpon>
		</Compile>
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\..\SasaLibDNet8\SasaLibDNet8.ArcSuitePreview\SasaLibDNet8.ArcSuitePreview.csproj" />
		<ProjectReference Include="..\..\..\SasaLibDNet8\SasaLibDNet8.MySQLConnect\SasaLibDNet8.MySQLConnect.csproj" />
		<ProjectReference Include="..\..\..\SasaLibDNet8\SasaLibDNet8.NumberingSupport\SasaLibDNet8.NumberingSupport.csproj" />
		<ProjectReference Include="..\..\..\SasaLibDNet8\SasaLibDNet8\SasaLibDNet8.csproj" />
		<ProjectReference Include="..\..\..\SasaLibTestFrame\SasaLib.DelegateWriteLine\SasaLib.DelegateWriteLine.csproj" />
		<ProjectReference Include="..\CommonTicketClassLibrary\CommonTicketClassLibraryDNet8.csproj" />
		<ProjectReference Include="..\FieldValueSet\FieldValueSetDNet8.csproj" />
		<ProjectReference Include="..\RemoteClientCADtype\RemoteClientCADtypeDNet8.csproj" />
		<ProjectReference Include="..\RemoteClient\RemoteClientDNet8.csproj" />
		<ProjectReference Include="..\RemoteObjects\RemoteObjectsDNet8.csproj" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
		<PackageReference Include="System.Buffers" Version="4.6.0" />
		<PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
		<PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
		<PackageReference Include="System.IO.Packaging" Version="9.0.0" />
		<PackageReference Include="System.Management" Version="9.0.0" />
		<PackageReference Include="System.Memory" Version="4.6.0" />
		<PackageReference Include="System.Text.Encodings.Web" Version="9.0.0" />
		<PackageReference Include="System.Threading.Tasks.Extensions" Version="4.6.0" />
	</ItemGroup>
	<ItemGroup>
	  <EmbeddedResource Update="Properties\Resources.resx">
	    <Generator></Generator>
	  </EmbeddedResource>
	</ItemGroup>
	<ItemGroup>
	  <None Update="Properties\Settings.settings">
	    <Generator>SettingsSingleFileGenerator</Generator>
	    <LastGenOutput>Settings.Designer.cs</LastGenOutput>
	  </None>
	</ItemGroup>
	<Import Project="..\..\STAGINGSYSTEM.AssemblyVersion\SasaLibDNet8.AssemblyVersion.projitems" Label="Shared" />
</Project>